version: '3.8'

services:
  postgres:
    image: postgres
    container_name: lexicon-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - '${DATABASE_PORT}:5432'
