name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - next-v*
      - develop
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        # creates a .env so node does not throw error
        run: touch .env && pnpm test
        env:
          DATABASE_PASSWORD: secretpassword
          DATABASE_USER: postgres
          DATABASE_NAME: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          PORT: 8080
          COOKIE_PASSWORD: YourPasswortMustBeAtLeast32Charc
